x-db-variables: &db-env
  ConnectionStrings__Database: Host=postgres;Port=5432;Database=notification_db;Username=admin;Password=admin
  ConnectionStrings__ReadOnlyDatabase: Host=postgres;Port=5432;Database=notification_db;Username=admin;Password=admin

x-rabbitmq-variables: &rabbit-env
  RABBITMQ__HOST: rabbitmq
  RABBITMQ__PORT: 5672
  RABBITMQ__USERNAME: guest
  RABBITMQ__PASSWORD: guest

x-reddis-variables: &redis-env
  REDIS__HOST: redis:6379

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc: 65536
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres:
    image: postgres:17
    container_name: notification-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: notification_db
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d notification_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: notification-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5


  dbmigrator:
    image: dbmigrator
    build:
      context: .
      dockerfile: DbMigrator/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # noinspection ComposeUnknownValues
      <<: [ *db-env ]

  api:
    image: notificationapi
    build:
      context: .
      dockerfile: NotificationApi/Dockerfile
    container_name: notification-api
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      dbmigrator:
        condition: service_completed_successfully
    environment:
      # noinspection ComposeUnknownValues
      <<: [ *rabbit-env, *db-env, *redis-env ]
      ASPNETCORE_URLS: http://+:8080

  notificationorchestrator:
    image: notificationorchestrator
    build:
      context: .
      dockerfile: NotificationOrchestrator/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      dbmigrator:
        condition: service_completed_successfully
    environment:
      # noinspection ComposeUnknownValues
      <<: [ *rabbit-env, *db-env, *redis-env ]

#  notificationworkeremail:
#    image: notificationworker
#    build:
#      context: .
#      dockerfile: NotificationWorker.Email/Dockerfile
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#      dbmigrator:
#        condition: service_completed_successfully
#    environment:
#      # noinspection ComposeUnknownValues
#      <<: [ *rabbit-env, *redis-env ]
#
#  notificationworkersms:
#    image: notificationworker
#    build:
#      context: .
#      dockerfile: NotificationWorker.SMS/Dockerfile
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
#      dbmigrator:
#        condition: service_completed_successfully
#    environment:
#      # noinspection ComposeUnknownValues
#      <<: [ *rabbit-env, *redis-env ]
#
#  notificationworkerpush:
#    image: notificationworker
#    build:
#      context: .
#      dockerfile: NotificationWorker.Push/Dockerfile
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
#      dbmigrator:
#        condition: service_completed_successfully
#    environment:
#      # noinspection ComposeUnknownValues
#      <<: [ *rabbit-env, *redis-env ]

volumes:
  postgres_data:
  redis_data: