<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Common\Common.csproj" />
      <ProjectReference Include="..\Persistence\Persistence.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="NotificationDbContext.ModelMapper.cs">
        <DependentUpon>NotificationDbContext.cs</DependentUpon>
      </Compile>
      <Compile Update="NotificationDbContext.ReadOnly.cs">
        <DependentUpon>NotificationDbContext.cs</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
