<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>NotificationWorker.Push</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Hosting\Hosting.csproj" />
      <ProjectReference Include="..\Integrations.RabbitMQ\Integrations.RabbitMQ.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Hosting" />
    </ItemGroup>

</Project>
